{% set name = "healpy" %}
{% set version = "1.17.1" %}
{% set sha256 = "6469fc9669e4cc6068c1509ba67228f215db57b3c2d6f00bd1eb481d97732e88" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - macos-c++-linking.patch    # [osx]
    - cross-rpath-flag-workaround.patch  # [aarch64]

build:
  number: 0
  skip: true  # [win or py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pkg-config
    - openssl
    - libopenssl-static
    - libtool  # [unix]
    - make  # [unix]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cfitsio
    - cython
    - python
    - setuptools
    - setuptools-scm
    - numpy
    - pip
    - pytest-runner
    - zlib
  run:
    - python
    - matplotlib-base
    - astropy
    - scipy
    - pytest-runner

test:
  imports:
    - healpy
    - healpy.test
  requires:
    - pytest
    - nose

about:
  home: http://github.com/healpy
  license: GPL-2.0-only
  license_file: COPYING
  summary: Healpix tools package for Python
  doc_url: http://healpy.readthedocs.org/
  dev_url: http://github.com/healpy/healpy

extra:
  recipe-maintainers:
    - lpsinger
    - mwcraig
    - pkgw
    - zonca
