{% set name = "healpy" %}
{% set version = "1.15.0" %}
{% set sha256 = "e09300a9f24e40b07f09ca7a7026d640a0478960b6ca6a5fc85052c0bb4335bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - macos-c++-linking.patch    # [osx]
    - cross-rpath-flag-workaround.patch  # [aarch64]

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pkg-config
    - openssl
    - libopenssl-static
    - libtool  # [unix]
    - make  # [unix]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cfitsio
    - cython
    - python
    - setuptools
    - numpy
    - pip
    - pytest-runner
    - six
  run:
    - python
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - six
    - astropy
    - scipy
    - pytest-runner

test:
  imports:
    - healpy
    - healpy.test
  requires:
    - pytest
    - nose

about:
  home: http://github.com/healpy
  license: GPL-2.0-only
  license_file: COPYING
  summary: Healpix tools package for Python
  doc_url: http://healpy.readthedocs.org/
  dev_url: http://github.com/healpy/healpy

extra:
  recipe-maintainers:
    - lpsinger
    - mwcraig
    - pkgw
    - zonca
